[package]
name = "polkadot-runtime-parachains"
version = "0.8.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
bitvec = { version = "0.20.1", default-features = false, features = ["alloc"] }
parity-scale-codec = { version = "2.0.0", default-features = false, features = ["derive"] }
log = "0.4.13"
rustc-hex = { version = "2.1.0", default-features = false }
serde = { version = "1.0.123", features = [ "derive" ], optional = true }
derive_more = "0.99.11"

sp-api = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix", default-features = false }
inherents = { package = "sp-inherents", git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix", default-features = false }
sp-std = { package = "sp-std", git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix", default-features = false }
sp-io = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix", default-features = false }
sp-runtime = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix", default-features = false }
sp-session = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix", default-features = false }
sp-staking = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix", default-features = false }
sp-core = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix", default-features = false }
sp-keystore = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix", optional = true }

pallet-authority-discovery = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix", default-features = false }
pallet-authorship = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix", default-features = false }
pallet-balances = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix", default-features = false }
pallet-session = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix", default-features = false }
frame-support = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix", default-features = false }
pallet-staking = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix", default-features = false }
frame-system = {git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix", default-features = false }
pallet-timestamp = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix", default-features = false }
pallet-vesting = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix", default-features = false }
pallet-offences = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix", default-features = false }
frame-benchmarking = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix", default-features = false, optional = true }

xcm = { package = "xcm", path = "../../xcm", default-features = false }
xcm-executor = { package = "xcm-executor", path = "../../xcm/xcm-executor", default-features = false }
primitives = { package = "polkadot-primitives", path = "../../primitives", default-features = false }
libsecp256k1 = { version = "0.3.5", default-features = false, optional = true }

rand = { version = "0.8.3", default-features = false }
rand_chacha = { version = "0.3.0", default-features = false }

[dev-dependencies]
futures = "0.3.12"
hex-literal = "0.3.1"
keyring = { package = "sp-keyring", git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix" }
sp-trie = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix" }
pallet-babe = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix" }
sp-application-crypto = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix" }
pallet-randomness-collective-flip = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix" }
pallet-staking-reward-curve = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix" }
pallet-treasury = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix" }
serde_json = "1.0.61"
libsecp256k1 = "0.3.5"
sp-version = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix", default-features = false }
sc-keystore = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix"}


[features]
default = ["std"]
no_std = []
std = [
	"bitvec/std",
	"parity-scale-codec/std",
	"rustc-hex/std",
	"serde",
	"primitives/std",
	"inherents/std",
	"sp-core/std",
	"sp-api/std",
	"sp-keystore",
	"sp-std/std",
	"sp-io/std",
	"frame-support/std",
	"pallet-authorship/std",
	"pallet-balances/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-staking/std",
	"pallet-session/std",
	"pallet-staking/std",
	"frame-system/std",
	"pallet-timestamp/std",
	"pallet-vesting/std",
	"xcm/std",
	"xcm-executor/std",
]
runtime-benchmarks = [
	"libsecp256k1/hmac",
	"frame-benchmarking",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
]
