[package]
name = "polkadot-node-core-proposer"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
futures = "0.3.12"
futures-timer = "3.0.2"
tracing = "0.1.22"
polkadot-node-subsystem = { path = "../../subsystem" }
polkadot-overseer = { path = "../../overseer" }
polkadot-primitives = { path = "../../../primitives" }
sc-basic-authorship = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix" }
sc-block-builder = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix" }
sc-client-api = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix" }
sp-api = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix" }
sp-blockchain = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix" }
sp-consensus = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix" }
sp-core = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix" }
sp-inherents = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix" }
sp-runtime = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix" }
sp-transaction-pool = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix" }
prometheus-endpoint = { package = "substrate-prometheus-endpoint", git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix" }
