[package]
name = "polkadot-rpc"
version = "0.8.28"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
jsonrpc-core = "15.1.0"
polkadot-primitives = { path = "../primitives" }
sc-client-api = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix"  }
sp-blockchain = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix"  }
sp-keystore = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix"  }
sp-runtime = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix"  }
sp-api = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix"  }
sp-consensus = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix"  }
sp-consensus-babe = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix"  }
sc-chain-spec = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix" }
sc-rpc = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix" }
sc-consensus-babe = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix"}
sc-consensus-babe-rpc = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix"}
sc-consensus-epochs = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix"}
sc-finality-grandpa = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix" }
sc-finality-grandpa-rpc = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix" }
sc-keystore = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix"}
sc-sync-state-rpc = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix"}
txpool-api = { package = "sp-transaction-pool", git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix" }
frame-rpc-system = { package = "substrate-frame-rpc-system", git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix"  }
pallet-transaction-payment-rpc = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix" }
parity-scale-codec = { version = "2.0.0", default-features = false }
sp-block-builder = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix" }
