[package]
name = "polkadot-rpc"
version = "0.8.27"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
jsonrpc-core = "15.1.0"
polkadot-primitives = { path = "../primitives" }
sc-client-api = { git = "https://github.com/tomaka/polkadot", branch = "rework-priority-groups-take2"  }
sp-blockchain = { git = "https://github.com/tomaka/polkadot", branch = "rework-priority-groups-take2"  }
sp-keystore = { git = "https://github.com/tomaka/polkadot", branch = "rework-priority-groups-take2"  }
sp-runtime = { git = "https://github.com/tomaka/polkadot", branch = "rework-priority-groups-take2"  }
sp-api = { git = "https://github.com/tomaka/polkadot", branch = "rework-priority-groups-take2"  }
sp-consensus = { git = "https://github.com/tomaka/polkadot", branch = "rework-priority-groups-take2"  }
sp-consensus-babe = { git = "https://github.com/tomaka/polkadot", branch = "rework-priority-groups-take2"  }
sc-chain-spec = { git = "https://github.com/tomaka/polkadot", branch = "rework-priority-groups-take2" }
sc-rpc = { git = "https://github.com/tomaka/polkadot", branch = "rework-priority-groups-take2" }
sc-consensus-babe = { git = "https://github.com/tomaka/polkadot", branch = "rework-priority-groups-take2"}
sc-consensus-babe-rpc = { git = "https://github.com/tomaka/polkadot", branch = "rework-priority-groups-take2"}
sc-consensus-epochs = { git = "https://github.com/tomaka/polkadot", branch = "rework-priority-groups-take2"}
sc-finality-grandpa = { git = "https://github.com/tomaka/polkadot", branch = "rework-priority-groups-take2" }
sc-finality-grandpa-rpc = { git = "https://github.com/tomaka/polkadot", branch = "rework-priority-groups-take2" }
sc-keystore = { git = "https://github.com/tomaka/polkadot", branch = "rework-priority-groups-take2"}
sc-sync-state-rpc = { git = "https://github.com/tomaka/polkadot", branch = "rework-priority-groups-take2"}
txpool-api = { package = "sp-transaction-pool", git = "https://github.com/paritytech/substrate", branch = "master" }
frame-rpc-system = { package = "substrate-frame-rpc-system", git = "https://github.com/paritytech/substrate", branch = "master"  }
pallet-transaction-payment-rpc = { git = "https://github.com/tomaka/polkadot", branch = "rework-priority-groups-take2" }
parity-scale-codec = { version = "1.3.5", default-features = false }
sp-block-builder = { git = "https://github.com/tomaka/polkadot", branch = "rework-priority-groups-take2" }
