[package]
name = "polkadot-core-primitives"
version = "0.7.30"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
sp-core = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix", default-features = false }
sp-std = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix", default-features = false }
sp-runtime = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix", default-features = false }
parity-scale-codec = { version = "2.0.0", default-features = false, features = [ "derive" ] }
parity-util-mem = { version = "0.9.0", default-features = false, optional = true }

[features]
default = [ "std" ]
std = [
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
	"parity-scale-codec/std",
	"parity-util-mem",
]
