[package]
name = "polkadot-statement-table"
version = "0.8.28"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
parity-scale-codec = { version = "2.0.0", default-features = false, features = ["derive"] }
sp-core = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix" }
primitives = { package = "polkadot-primitives", path = "../primitives" }
