[package]
name = "polkadot-statement-table"
version = "0.8.27"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
parity-scale-codec = { version = "1.3.5", default-features = false, features = ["derive"] }
sp-core = { git = "https://github.com/tomaka/polkadot", branch = "rework-priority-groups-take2" }
primitives = { package = "polkadot-primitives", path = "../primitives" }
