[package]
name = "polkadot-node-core-approval-voting"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
futures = "0.3.8"
parity-scale-codec = { version = "2.0.0", default-features = false, features = ["bit-vec", "derive"] }

polkadot-subsystem = { package = "polkadot-node-subsystem", path = "../../subsystem" }
polkadot-overseer = { path = "../../overseer" }
polkadot-primitives = { path = "../../../primitives" }
polkadot-node-primitives = { path = "../../primitives" }
bitvec = "0.20.1"

sc-client-api = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix", default-features = false }
sp-consensus-slots = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix", default-features = false }
sp-blockchain = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix", default-features = false }

[dev-dependencies]