[package]
name = "polkadot-erasure-coding"
version = "0.8.28"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
primitives = { package = "polkadot-primitives", path = "../primitives" }
reed_solomon = { package = "reed-solomon-erasure", version = "4.0.2" }
parity-scale-codec = { version = "2.0.0", default-features = false, features = ["derive"] }
sp-core = { git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix" }
trie = { package = "sp-trie", git = "file:///home/cecile/repos/substrate", branch = "cecton-test-bug-missing-prefix" }
thiserror = "1.0.23"
